use_map_topic: true

min_particles: 500
max_particles: 5000 ### 2000
kld_err: 0.05
kld_z: 0.99
update_min_d: 0.25      ### 0.25
update_min_a: 0.2      ### 0.2
resample_interval: 1
## Increase tolerance because the computer can get quite busy 
transform_tolerance: 0.2  ###1.0
recovery_alpha_slow: 0.001
recovery_alpha_fast: 0.1
aser_z_short: 0.05
gui_publish_rate: 10.0

scan_topic: "/scan"
laser_max_range: -1.0  #Laser Range
laser_min_range: -1.0  #Laser Range
laser_max_beams: 180
laser_z_hit: 0.95      ####0.95
laser_z_short: 0.05
laser_z_max: 0.05 
laser_z_rand: 0.05    #z_rand部分的权重，默认0.05。随机噪声的权重。（如声呐的多次反射，传感器串扰）
laser_sigma_hit: 0.2  #用在模型的z_hit部分的高斯模型的标准差，默认0.2m
laser_lambda_short: 0.1
laser_likelihood_max_dist: 8.0
laser_model_type: "likelihood_field" # "likelihood_field" or "beam"
#光束模型使用所有4：Z_HIT、z_Short、z_max和z_rand。似然场模型只使用2：Z_HIT和z_rand。使用中的权重和应等于1。

# dist —— laser_likelihood_max_dist
# σ —— laser_sigma_hit
# prob为laser_likelihood_max_dist为中心标准方差为σ（laser_sigma_hit）的高斯分布的距离概率）
# 那么观测到z的概率 p = laser_z_hit * prob(dist, σ) + laser_z_rand * p_rand;


## Publish scans from best pose at a max of 10 Hz
odom_model_type: "diff"
odom_alpha1: 0.2
odom_alpha2: 0.2
## translation std dev, m 
odom_alpha3: 0.3  ### 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1
odom_frame_id: "odom"
base_frame_id: "base_footprint"
global_frame_id: "map"

